baseURL = "https://biwashi.github.io/blog/"
languageCode = "ja"
title = "MY NEW GEAR | IWASHI BLOG" # Homeのタイトル
theme = "timer-hugo"
publishDir = "docs"
canonifyurls = true # 相対URLを絶対URLに変換できるようにする

# pygmentsUseClasses = true
# pygmentsCodefences = true 

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Skill"
url     = "skill"
weight  = 3
# [[menu.main]]
# name    = "Gallery"
# url     = "gallery"
# weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
# [[menu.main]]
# name    = "Contact"
# url     = "contact"
# weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/iwashimiddle.png" # homeのLogoを設定
dateFormat = "6 January 2006" #??
# Meta data
description = "Airspace Hugo theme"
author = "作者を書く"
# Google Analitycs
googleAnalitycsID = "G-PEBYWXRR3K" # Google Anlaycs用のIDを設定できる
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io formを設定する用
# Disqusによるコメント機能実装用
disqusShortname = "ShortName"

# Banner Section
[params.banner]
enable  = true
bgImage = "images/headphone.jpg" # バナーの画像
heading = "MY NEW GEAR..."
description = "This is My Blog"
# button
# btn     = true
btnText = "何かをさせるボタン"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "Shota Iwami"
[[params.banner.flipText]]
title   = "いわみ しょうた"
[[params.banner.flipText]]
title   = "イワミ ショウタ"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "<h3>Iwami Shota 岩見彰太</h3><br>Hello, My name is Shota Iwami.<br> I'm 23 years old, a graduate studentat Tokyo Metropolitan University and living in Yokohama.<br><br>大学でドローンの航空交通管理（UTM）の研究をしながら、長期インターンでドローン開発をしたり、ハッカソンに出たり、WEB開発をほげほげやったりしてます。<br>WEB開発のいろんな記録としてのあれこれや書いたり、カメラやジンバル、ドローンやオーディオ機器などの好きなガジェットのレビューなどつらつらと投稿していくつもりです。"
image   = "images/about/about-me.jpg"

# Call to Action
[params.cta]
# enable  = true
title   = "SO WHAT YOU THINK ?"
content = "コンタクトしてくれ<br>ここはhtmlで上書きできる<br><h3>やほーー"
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
# enable  = true
title   = "ポートフォリオ"
subtitle= "Portfolio"

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/jazzy.yuzax/"

[[params.socialIcon]]
icon = "ion-social-github"
url = "https://github.com/BIwashi"

[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/B_Sardine"

# # Indexの表示設定
[markup]
    [markup.tableOfContents]
        # endLevel = 2
        # ordered = true
        # startLevel = 2
        
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true